import json
import os

from dotenv import load_dotenv
from openai import OpenAI


class LLMClient:
    """
    Handles communication with the OpenAI Responses API.
    """

    def __init__(self):
        load_dotenv()

        api_key = os.getenv("OPENAI_API_KEY")

        if not api_key:
            raise ValueError(
                "OPENAI_API_KEY not found. Please add it to your .env file."
            )

        self.client = OpenAI(api_key=api_key)

    def generate_query(self, messages: list) -> dict:
        """
        Sends the prompt to the OpenAI API and returns the
        structured JSON generated by the model.
        """

        try:
            response = self.client.responses.create(
                model="gpt-4.1-mini",
                input=messages,
                temperature=0,
            )
        except Exception as error:
            raise RuntimeError(
                f"Failed to communicate with the OpenAI API.\n\n{error}"
            ) from error

        output_text = getattr(response, "output_text", None)

        if not output_text:
            raise ValueError(
                "The model returned an empty response."
            )

        output_text = output_text.strip()

        try:
            structured_query = json.loads(output_text)
        except json.JSONDecodeError as error:
            raise ValueError(
                "The model returned invalid JSON.\n\n"
                f"Response received:\n\n{output_text}"
            ) from error

        if not isinstance(structured_query, dict):
            raise ValueError(
                "The model response must be a JSON object."
            )

        return structured_query